DROP TABLE IF EXISTS SPACE_TRAVEL;
CREATE TABLE SPACE_TRAVEL (
  id    BIGINT SERIAL PRIMARY KEY,
  destination VARCHAR(32) NOT NULL,
  distance BIGINT NOT NULL
);

DROP TABLE IF EXISTS RESEARCH;
CREATE TABLE RESEARCH (
  id    BIGINT SERIAL PRIMARY KEY,
  space_travel_id BIGINT NOT NULL REFERENCES SPACE_TRAVEL(id),
  description VARCHAR(255) NOT NULL
);